language: python

sudo: required

services:
  - docker

env:
  global:
    - REPO=wodby/drupal-php
    - LATEST_DRUPAL=8
    - LATEST_PHP=7.1
  matrix:
    - DRUPAL=6 PHP=5.3
    - DRUPAL=6 PHP=5.6
    - DRUPAL=7 PHP=5.6
    - DRUPAL=7 PHP=7.0
    - DRUPAL=7 PHP=7.1
    - DRUPAL=8 PHP=7.0
    - DRUPAL=8 PHP=7.1

script:
  - cd ./$DRUPAL/$PHP
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make VERSION="$DRUPAL-$PHP-$TRAVIS_TAG" release
    fi

    if [ "$DRUPAL" == "$LATEST_DRUPAL" && "$PHP" == "$LATEST_PHP" ]; then
      make VERSION=latest release
    fi
  fi

after_failure: make logs

notifications:
  email:
    on_success: never
    on_failure: always
